language: csharp
solution: XMLUnit.NET.NetFramework.sln
matrix:
  include:
    - dotnet: 2.1.200
      mono: none
      script:
        - dotnet restore XMLUnit.NET.sln
        - dotnet build XMLUnit.NET.sln -c Debug
        - dotnet test src/tests/net-core/XMLUnit.Core.Tests.csproj
        - dotnet test src/tests/net-constraints-nunit3/XMLUnit.NUnit3.Constraints.Test.csproj
        - dotnet test src/tests/net-placeholders/XMLUnit.Placeholders.Tests.csproj
    - mono: latest
      script:
        - xbuild XMLUnit.NET.NetFramework.sln

notifications:
  email:
    - xmlunit-commits@lists.sourceforge.net
